### PR TITLE
Add: WPAcceptance testing

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
Add acceptance testing using 10up/wpacceptance.

### Alternate Designs
n/a

### Benefits
Give us more confidence when shipping releases.

### Possible Drawbacks
n/a

### Verification Process
See the CI passed.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@dinhtungdu the block on this PR from #36 should be gone now that 36 has been merged in

**Comment by dinhtungdu** [comment]
@jeffpaul Yes, working on this to add more test cases

**Comment by dinhtungdu** [comment]
@jeffpaul The test case for reordering child pages is falling, and it's expected behavior due to #43

**Comment by helen** [comment]
I am merging this first - the tests will fail on `develop`, and then after merging #51 and #53 they should pass.

**Pull request merged**
