### PR TITLE
Bump WordPress "tested up to" version 6.4

### LINKED ISSUE #171: The plugin hasn't been tested with an upcoming version of WordPress
There is an upcoming WordPress version in the **release candidate** stage that the plugin hasn't been tested with. Please test it and then change the "Tested up to" field in the plugin readme.

**Tested up to:** 6.3
**Upcoming version:** 6.4

This issue will be closed automatically when the versions match.

### PR DESCRIPTION
**Pull request by jeffpaul**
### Description of the Change
Bumps WordPress "tested up to" version 6.4

Closes #171.

### Changelog Entry

> Changed - Bump WordPress "tested up to" version 6.4.

### Credits

Props @qasumitbagthariya @jeffpaul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@qasumitbagthariya I'm seeing failures on `trunk` when bumping to WP 6.4.  Are you certain your tests passed?

**Comment by qasumitbagthariya** [comment]
@jeffpaul 
It works for [2.6.0](https://github.com/10up/simple-page-ordering/releases/tag/2.6.0) but does not work with the trunk branch.

**Review by faisal-alvi — APPROVED** [review]
I re-ran the tests and they [passed](https://github.com/10up/simple-page-ordering/actions/runs/6750615979/job/18394052539?pr=177) this time.

Approving, not tested the plugin thoroughly.

@qasumitbagthariya can you please test again and then it'll be good to merge?

**Comment by qasumitbagthariya** [comment]
@faisal-alvi 

The functionality works when downloading the plugin from https://wordpress.org/plugins/simple-page-ordering/ but looks like an issue when we download from the git [release](https://github.com/10up/simple-page-ordering/releases) zip and trunk branch.

Can you please check from your end?

The issue is not a blocker for this PR so I'm approving this PR. ✅ 

cc @jeffpaul

**Comment by faisal-alvi** [comment]
> The issue is not a blocker for this PR so I'm approving this PR.

@qasumitbagthariya since the issue doesn't seem to be related to WordPress 6.4, could you please open a separate issue ticket for it? Once that's done, we can merge this PR.

**Comment by qasumitbagthariya** [comment]
@faisal-alvi 

Already the Issue has been created https://github.com/10up/simple-page-ordering/issues/178

**Review by qasumitbagthariya — APPROVED** [review]

**Pull request merged**
