### PR TITLE
Add: Pre-commit hooks

### LINKED ISSUE #40: Add precommit hooks
**Is your enhancement related to a problem? Please describe.**

We don't run any linter before committing for now. This may lead to inconsistent coding styling and syntax errors get committed.

**Describe the solution you'd like**

Add precommit hooks and linters to this project.

**Designs**

Use husky and lint-staged for precommit hooks. Use `eslint` for JS and `phpcs` for PHP files.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
Add pre-commit hooks and linters to keep the coding style of this project consistent and prevent potential syntax error early.

### Alternate Designs
n/a

### Benefits
New code is checked before committing.

### Possible Drawbacks
We may need to update Github action workflows to match with new changes.

### Verification Process
- See new files `composer.json` and `composer.lock` in repo.
- Make test changes to `simple-page-ordering.php`, stage it, commit it, see the pre-commit hooks run.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
Closes #40

### CODE REVIEW

**Comment by jeffpaul** [comment]
@dinhtungdu can you resolve the conflicts here so we can work to get this and #42 merged?

**Comment by dinhtungdu** [comment]
@jeffpaul sure! Fixed conflicts.

**Comment by helen** [comment]
I don't want to do this in a hotfix release, also seems to me if we're adding linting that should be added to CI. Punting to 2.4.

**Comment by dinhtungdu** [comment]
Closing. We should implement #79 first then rework this PR.

**Pull request closed without merging**
