### PR TITLE
Ensure draggable placeholder has same column structure as dragged item.

### PR DESCRIPTION
**Pull request by benhuson**
Fresh PR for https://github.com/jakemgold/simple-page-ordering/pull/7

This PR copies the column structure of the dragged item, empties all the cell content and uses that as the placeholder to ensure the table structure is preserved. This prevents the page jump for a much smoother experience.

### CODE REVIEW

**Comment by adamsilverstein** [comment]
This works well in my testing, going to review code and what it changes next.

Before:




After:

**Comment by adamsilverstein** [comment]
@benhuson Thanks for the PR! I tested this out and while it works well, it can be simplified a bit. The placeholder we are setting here is the string that jQuery UI uses for the blank space showing where you are about to drop the item you are dragging. By default this is constructed from the dragged element and this is what your code fixes. A simpler more solid/safer fix is just clearing the placeholder directly, see https://github.com/10up/simple-page-ordering/commit/8585aec4d3f9b8ab10bd3cc5666dfffbf09bc5c3 - in my testing this has the exact same results as your code.

Can you please update your PR with this approach (or open it so I can) and I'll happily merge!

Thanks.

**Comment by benhuson** [comment]
@adamsilverstein Works well for me - I'e made the changes :)

**Comment by adamsilverstein** [comment]
Perfect, thanks @benhuson!

**Pull request merged**
